POST http://localhost:8080/movie-api/add
Content-Type: application/json

{
  "name" : "test1",
  "description" : "test description",
  "type" : "Полнометражный",
  "genre" : "Комедия",
  "releaseDate": "28-07-2005"

}

###
